name:                template-haskell-project
version:             0.1.0.0
github:              "habedi/template-haskell-project"
license:             MIT
author:              "Author Name"
maintainer:          "author@example.com"
copyright:           "2024 Author Name"

extra-source-files:
  - README.md
  - LICENSE

synopsis:            A simple Haskell project template
category:            Template
description:         Please see the README on GitHub at <https://github.com/habedi/template-haskell-project#readme>

dependencies:
  - base >= 4.14 && < 5
  - text >= 1.2 && < 3

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  template-haskell-project:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - template-haskell-project

tests:
  template-haskell-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - template-haskell-project
      - hspec >= 2.7 && < 3
      - QuickCheck >= 2.14 && < 3
